### ISSUE TITLE
[BUG]win11 wsl2 Ubuntu下安装报错 

### ISSUE THREAD

**Issue by TesterPi** [metersphere/metersphere#14271]
### MeterSphere 版本

V1.20.4

### 使用外置数据库

否

### 问题描述

部署时报错：Error response from daemon: failed to mount local volume: mount /opt/metersphere/data/redis:/var/lib/docker/volumes/metersphere_ms-redis-data/_data, flags: 0x1000: no such file or directory

### 重现步骤

下载安装包在win11 wsl2 Ubuntu系统上面按照部署文档进行安装

### 附加信息

<img width="1280" alt="屏幕截图 2022-06-01 133800" src="https://user-images.githubusercontent.com/77143050/171335235-0ac08eb9-c165-4bc5-9948-6ed28da96762.png">
<img width="705" alt="屏幕截图 2022-06-01 133912" src="https://user-images.githubusercontent.com/77143050/171335251-78d2e21f-a1b4-4ba2-90b6-46e8be15a4ee.png">

**Comment by 2lipan** [comment]
见如下文档。
[Window10安装MeterSphere操作文档.pdf](https://github.com/metersphere/metersphere/files/8814462/Window10.MeterSphere.pdf)

**Comment by TesterPi** [comment]
按照文档改了下，容器起起来了，但是有报错，ms-server没有起起来，请问这里怎么改呢？/opt/metersphere/conf/metersphere.properties，这个路径下有这个文件。
<img width="1077" alt="屏幕截图 2022-06-02 110349" src="https://user-images.githubusercontent.com/77143050/171545059-247f0fa6-1179-451c-93cb-fbf34dbe5fb2.png">
<img width="689" alt="屏幕截图 2022-06-02 110929" src="https://user-images.githubusercontent.com/77143050/171545069-9b1bdead-cd2c-4d81-8962-2c1d825a6337.png">

**Comment by youliyuan-fit2cloud** [comment]
/opt/metersphere/conf/metersphere.properties 这个文件是不是变成目录? 可以新建一个同名文件 ：
复制如下内容：
#logger.sql.level=info
# PROPERTIES FOR METERSPHERE SERVER 
## DATABASE
#spring.datasource.url=jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#spring.datasource.username=${MS_MYSQL_USER}
#spring.datasource.password=${MS_MYSQL_PASSWORD}

## KAFKA
#kafka.partitions=1
#kafka.replicas=1
#kafka.topic=${MS_KAFKA_TOPIC}
#kafka.bootstrap-servers=${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
#kafka.log.topic=${MS_KAFKA_LOG_TOPIC}


# PROPERTIES FOR METERSPHERE NODE CONTROLLER
## JMETER
#jmeter.image=registry.fit2cloud.com/metersphere/jmeter-master:0.0.7


## CAS
#cas.client.name=MS_SERVER
## CAS SERVER URL
#cas.server.url=http://xxx/cas
## METERSPHERE SERVER URL
#cas.client.url=http://IP:8081

**Comment by TesterPi** [comment]
把这段在docker-compose-server.yml文件中注释掉，仍然在报相同的错误
<img width="723" alt="屏幕截图 2022-06-02 175931" src="https://user-images.githubusercontent.com/77143050/171606478-8cb5d69f-b028-4b59-8f50-69ae9efdb84f.png">

**Comment by youliyuan-fit2cloud** [comment]
> metersphere.properties是一个文件，/opt/metersphere/conf/metersphere.properties这个路径好像是指的容器内的路径，但是现在进不到容器

请参考这个步骤试试吧
/opt/metersphere/conf/metersphere.properties 可以新建一个metersphere.properties 文件 ：
文件内容如下：
[msproper-file.docx](https://github.com/metersphere/metersphere/files/8821885/msproper-file.docx)

然后重启服务

**Comment by TesterPi** [comment]
> > metersphere.properties是一个文件，/opt/metersphere/conf/metersphere.properties这个路径好像是指的容器内的路径，但是现在进不到容器
> 
> 请参考这个步骤试试吧, cd /opt/metersphere/conf/ #新建一个metersphere.properties 文件 ： vim metersphere.properties #文件内容如下： [msproper-file.docx](https://github.com/metersphere/metersphere/files/8821885/msproper-file.docx)
> 
> 然后重启服务

执行了，还是报相同的错误

**Comment by wangzhen-fit2cloud** [comment]
你好，可以试着保持之前的 volume 配置，然后修改下 docker-compose-server.yaml，将启动命令改为 “top” 让容器可以正常启动后，通过 exec 命令去到容器里面再观察下。
```yaml
version: "2.1"
services:
  ms-server:
    image: ${MS_IMAGE_PREFIX}/metersphere:${MS_IMAGE_TAG}
    container_name: ms-server
    command: "top"
# 其他内容
```
```sh
docker exec -it ms-server sh
```

**Comment by TesterPi** [comment]
加上command命令后能够进入到容器内部，然后查看了下/opt/metersphere/conf 这个路径下没有metersphere.properties 这个文件。从容器外部把这个文件拷贝到容器内部，然后重启后仍然报错。重启后拷贝进容器内的文件metersphere.properties会自动清除掉。
<img width="209" alt="image" src="https://user-images.githubusercontent.com/77143050/172511292-b84a604f-d460-40a5-bb07-4f734db14494.png">

**Comment by wangzhen-fit2cloud** [comment]
麻烦将现在使用的 compose 文件内容提供下？

**Comment by TesterPi** [comment]
`version: "2.1"
services:
  ms-server:
    image: ${MS_IMAGE_PREFIX}/metersphere:${MS_IMAGE_TAG}
    container_name: ms-server
    command: "top"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      JMETER_IMAGE: ${MS_JMETER_IMAGE}
      K8S_NODE-CONTROLLER-IMAGE: ${MS_IMAGE_PREFIX}/ms-node-controller:${MS_IMAGE_TAG}
      TCP_MOCK_PORT: ${MS_TCP_MOCK_PORT}
      SESSION_TIMEOUT: 21600
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
      SPRING_SESSION_STORE-TYPE: redis
      SPRING_REDIS_HOST: ${MS_REDIS_HOST}
      SPRING_REDIS_PORT: ${MS_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
    ports:
      - ${MS_SERVER_PORT}:8081
      - ${MS_TCP_MOCK_PORT}:${MS_TCP_MOCK_PORT}
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8081"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf/opt/metersphere/conf
      - ${MS_BASE}/metersphere/logs/opt/metersphere/logs
      - ${MS_BASE}/metersphere/data/opt/metersphere/data
#    mem_limit: 1024m
    networks:
      - ms-network

  ms-data-streaming:
    image: ${MS_IMAGE_PREFIX}/ms-data-streaming:${MS_IMAGE_TAG}
    container_name: ms-data-streaming
    environment:
      HOST_HOSTNAME: $HOSTNAME
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8084"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ./conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${MS_BASE}/metersphere/logs/data-streaming:/opt/metersphere/logs/data-streaming
    networks:
      - ms-network
`

**Comment by TesterPi** [comment]
```
version: "2.1"
services:
  ms-server:
    image: ${MS_IMAGE_PREFIX}/metersphere:${MS_IMAGE_TAG}
    container_name: ms-server
    command: "top"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      JMETER_IMAGE: ${MS_JMETER_IMAGE}
      K8S_NODE-CONTROLLER-IMAGE: ${MS_IMAGE_PREFIX}/ms-node-controller:${MS_IMAGE_TAG}
      TCP_MOCK_PORT: ${MS_TCP_MOCK_PORT}
      SESSION_TIMEOUT: 21600
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
      SPRING_SESSION_STORE-TYPE: redis
      SPRING_REDIS_HOST: ${MS_REDIS_HOST}
      SPRING_REDIS_PORT: ${MS_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
    ports:
      - ${MS_SERVER_PORT}:8081
      - ${MS_TCP_MOCK_PORT}:${MS_TCP_MOCK_PORT}
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8081"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf/opt/metersphere/conf
      - ${MS_BASE}/metersphere/logs/opt/metersphere/logs
      - ${MS_BASE}/metersphere/data/opt/metersphere/data
#    mem_limit: 1024m
    networks:
      - ms-network

  ms-data-streaming:
    image: ${MS_IMAGE_PREFIX}/ms-data-streaming:${MS_IMAGE_TAG}
    container_name: ms-data-streaming
    environment:
      HOST_HOSTNAME: $HOSTNAME
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8084"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ./conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${MS_BASE}/metersphere/logs/data-streaming:/opt/metersphere/logs/data-streaming
    networks:
      - ms-network

```

**Comment by TesterPi** [comment]
> 麻烦将现在使用的 compose 文件内容提供下？

```
version: "2.1"
services:
  ms-server:
    image: ${MS_IMAGE_PREFIX}/metersphere:${MS_IMAGE_TAG}
    container_name: ms-server
    command: "top"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      JMETER_IMAGE: ${MS_JMETER_IMAGE}
      K8S_NODE-CONTROLLER-IMAGE: ${MS_IMAGE_PREFIX}/ms-node-controller:${MS_IMAGE_TAG}
      TCP_MOCK_PORT: ${MS_TCP_MOCK_PORT}
      SESSION_TIMEOUT: 21600
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
      SPRING_SESSION_STORE-TYPE: redis
      SPRING_REDIS_HOST: ${MS_REDIS_HOST}
      SPRING_REDIS_PORT: ${MS_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
    ports:
      - ${MS_SERVER_PORT}:8081
      - ${MS_TCP_MOCK_PORT}:${MS_TCP_MOCK_PORT}
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8081"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf/opt/metersphere/conf
      - ${MS_BASE}/metersphere/logs/opt/metersphere/logs
      - ${MS_BASE}/metersphere/data/opt/metersphere/data
#    mem_limit: 1024m
    networks:
      - ms-network

  ms-data-streaming:
    image: ${MS_IMAGE_PREFIX}/ms-data-streaming:${MS_IMAGE_TAG}
    container_name: ms-data-streaming
    environment:
      HOST_HOSTNAME: $HOSTNAME
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_PARTITIONS: 4
      KAFKA_REPLICAS: 1
      KAFKA_TOPIC: ${MS_KAFKA_TOPIC}
      KAFKA_LOG_TOPIC: ${MS_KAFKA_LOG_TOPIC}
      KAFKA_TEST_TOPIC: ${MS_KAFKA_TEST_TOPIC}
      KAFKA_REPORT_TOPIC: ${MS_KAFKA_REPORT_TOPIC}
      KAFKA_BOOTSTRAP-SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8084"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ./conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${MS_BASE}/metersphere/logs/data-streaming:/opt/metersphere/logs/data-streaming
    networks:
      - ms-network

```
