### ISSUE TITLE
[BUG] msctl uninstall -v 会将已部署的 jenkins 容器删除

### ISSUE THREAD

**Issue by zzkskys** [metersphere/metersphere#15332]
### 联系方式

2336276765@qq.com

### MeterSphere 版本

v1.20.8-lts

### 使用外置数据库

是

### 问题描述

` msctl uninstall -v` 会将已部署的 jenkins 容器删除

### 重现步骤

1. 通过 Docker 部署 Jenkins 容器，容器名称是 `jenkins` ,访问端口是 8080
2. 执行 `msctl uninstall -v` 
3.访问 jenkins 失败，查阅发现 docker 实例发现 jenkins 容器已删除

### 期待的正确结果

执行 `msctl uninstall -v` 时不会删除已经部署的 jenkins 容器

### 相关日志输出

```shell
暂未日志
```

### 附加信息

这是部署 jenkins 的 `docker-compose.yaml` : 
```yaml
version: '3'
services:
  
  jenkins:
    user: root
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
