### ISSUE TITLE
kubernetes 部署metersphere提示Image Not Found: metersphere/jmeter-master:5.4.3-ms5-jdk11

### ISSUE THREAD

**Issue by qddkk** [metersphere/metersphere#15626]
### 请描述您的问题

kubernetes部署metersphere提示Image Not Found: metersphere/jmeter-master:5.4.3-ms5-jdk11
![image](https://user-images.githubusercontent.com/59435662/177956719-39e1e005-baa5-40c2-a124-55a6a1e687c2.png)
我的ms-node-controller-deploy.yaml如下

```
#ms-node-controller-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-node-controller
  namespace: ms
spec:
  selector:
    matchLabels:
      app: ms-node-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-node-controller
    spec:
      containers:
        - name: ms-node-controller
          image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_HOSTNAME
              value: ms-node-controller
          ports:
            - containerPort: 8082
            - containerPort: 9100
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - name: ms-conf
              mountPath: /opt/metersphere/conf
            - name: ms-data
              mountPath: /opt/metersphere/data
            - name: ms-logs
              mountPath: /opt/metersphere/logs
            - name: ms-node-controller-sock
              mountPath: /var/run/docker.sock
        - name: nodeexporter
          image: registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:latest
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: nodeexporter-proc
              mountPath: /host/proc
              readOnly: true
            - name: nodeexporter-sys
              mountPath: /host/sys
              readOnly: true
            - name: nodeexporter-rootfs
              mountPath: /rootfs
              readOnly: true
      volumes:
        - name: nodeexporter-proc
          hostPath:
            path: /proc
        - name: nodeexporter-sys
          hostPath:
            path: /sys
        - name: nodeexporter-rootfs
          hostPath:
            path: /
        - name: ms-conf
          hostPath:
            path: /opt/nfs/metersphere/conf
        - name: ms-data
          hostPath:
            path: /opt/nfs/metersphere/data
        - name: ms-logs
          hostPath:
            path: /opt/nfs/metersphere/logs
        - name: ms-node-controller-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: ms-node-controller
  namespace: ms
spec:
  ports:
    - name: ms-node-8082
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: ms-node-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
  selector:
    app: ms-node-controller

```
请问应该如何修改呢
