### ISSUE TITLE
[BUG]helm升级错误

### ISSUE THREAD

**Issue by qiaolb** [metersphere/metersphere#27624]
### 联系方式

qiaolibo@126.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

是

### 问题描述

使用helm安装了2.8.1，执行升级到最新，提示错误：
```
helm upgrade metersphere metersphere/metersphere -n ms -f metersphere.yaml 
```

执行结果：
```
Error: UPGRADE FAILED: cannot patch "metersphere-data-pvc" with kind PersistentVolumeClaim: PersistentVolumeClaim "metersphere-data-pvc" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
- 	AccessModes: []core.PersistentVolumeAccessMode{"ReadWriteOnce"},
+ 	AccessModes: []core.PersistentVolumeAccessMode{"ReadWriteMany"},
  	Selector:    nil,
  	Resources:   {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
  	... // 5 identical fields
  }
 && cannot patch "node-controller-data-pvc" with kind PersistentVolumeClaim: PersistentVolumeClaim "node-controller-data-pvc" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
- 	AccessModes: []core.PersistentVolumeAccessMode{"ReadWriteOnce"},
+ 	AccessModes: []core.PersistentVolumeAccessMode{"ReadWriteMany"},
  	Selector:    nil,
  	Resources:   {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}},
  	... // 5 identical fields
  }
 && cannot patch "metersphere-kafka-headless" with kind Service: Service "metersphere-kafka-headless" is invalid: spec.ports[3].name: Duplicate value: "tcp-controller" && cannot patch "metersphere-kafka" with kind Service: Service "metersphere-kafka" is invalid: spec.ports[2].name: Duplicate value: "tcp-external"
```

### 重现步骤

之前通过Helm安装，这次进行升级。其中配置文件metersphere.yaml 内容如下：

```
ingress:
  host: metersphere.xxx.cn
  https:
    enabled: true
    secretName: xxx
common:
  storageClass: nfs-prod
  imagePullPolicy: IfNotPresent
mysql:
  enabled: false
  host: 192.168.0.xxx
  port: 3306
  username: xxx
  password: xxxxx
performanceTest:
  enabled: false
logPersistence:
  enabled: false
```

查询更新结果：

```
helm ls -n ms
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS	CHART             	APP VERSION
metersphere	ms       	6       	2023-11-20 15:20:03.462032638 +0800 CST	failed	metersphere-2.10.8	2.10.8-lts 
```
