### ISSUE TITLE
[BUG]在 aliyun ack serverless 版本中无法安装

### ISSUE THREAD

**Issue by fency12** [metersphere/metersphere#30909]
### 联系方式

582399232@qq.com

### MeterSphere 版本

metersphere-2.10.14.tgz

### 使用外置数据库

否

### 问题描述

在 aliyun ack serverless 版本中无法安装，如图
![图片](https://github.com/metersphere/metersphere/assets/19307432/17ad80c9-bd6f-45aa-860f-232252ce6bb4)
![图片](https://github.com/metersphere/metersphere/assets/19307432/2c3b243b-37ff-4923-9c00-f47baf8eab17)

### 重现步骤

首次安装，全部 helm

### 期待的正确结果

安装成功

**Comment by liuruibin** [comment]
还有其他信息可以提供吗？

**Comment by fency12** [comment]
需要哪些信息？

**Comment by liuruibin** [comment]
有没有具体报错

**Comment by fency12** [comment]
```yaml
[root@dev-jenkins fency]# kubectl -nms get po
NAME                                             READY   STATUS             RESTARTS         AGE
metersphere-api-test-7f5cc5b46f-drbjr            0/1     Init:2/4           0                135m
metersphere-data-streaming-69cf9dcd4f-x6g5w      1/1     Running            0                135m
metersphere-eureka-5d54c978d9-58pvg              1/1     Running            0                135m
metersphere-gateway-78899b8f6d-fj5fv             0/1     CrashLoopBackOff   21 (2m52s ago)   135m
metersphere-kafka-controller-0                   1/1     Running            0                135m
metersphere-node-controller-647c6cbdbd-95mtd     0/1     InvalidParameter   0                135m
metersphere-performance-test-5bc95b9c44-xzd8c    0/1     Init:2/4           0                135m
metersphere-project-management-87c84b56c-hfcl2   0/1     Init:2/4           0                135m
metersphere-report-stat-dd5968889-lbd4z          0/1     Init:2/4           0                135m
metersphere-system-setting-5bfc89b78b-9l24g      0/1     Init:2/3           0                135m
metersphere-test-track-7b784f694-lqrp8           0/1     Init:2/4           0                135m
metersphere-workstation-688d574bc-76rfb          0/1     Init:2/4           0                135m
minio-0                                          1/1     Running            0                135m
mysql-0                                          1/1     Running            0                135m
redis-0                                          1/1     Running            0                135m
[root@dev-jenkins fency]# kubectl -nms logs -f metersphere-node-controller-647c6cbdbd-95mtd
Defaulted container "metersphere-node-controller" out of: metersphere-node-controller, wait-kafka (init)
[root@dev-jenkins fency]# kubectl -nms describe po metersphere-gateway-78899b8f6d-fj5fv
Name:             metersphere-gateway-78899b8f6d-fj5fv
Namespace:        ms
Priority:         0
Service Account:  default
Node:             virtual-kubelet-cn-shanghai-b/10.30.1.130
Start Time:       Fri, 17 May 2024 15:53:10 +0800
Labels:           app=metersphere-gateway
                  pod-template-hash=78899b8f6d
Annotations:      ProviderCreate: done
                  k8s.aliyun.com/cluster-dns: 10.31.0.10
                  k8s.aliyun.com/cluster-domain: cluster.local
                  k8s.aliyun.com/dns-cache-enable: false
                  k8s.aliyun.com/eci-client-token: aae93dd7-1474-473d-8346-cfdf528b8a8c
                  k8s.aliyun.com/eci-container-exit-priority: {}
                  k8s.aliyun.com/eci-created-by-template: true
                  k8s.aliyun.com/eci-drop-apiserver-interactive-caps: 
                  k8s.aliyun.com/eci-instance-cpu: 0.25
                  k8s.aliyun.com/eci-instance-id: eci-uf6ix1mkn257aqa3gjnu
                  k8s.aliyun.com/eci-instance-mem: 1.0
                  k8s.aliyun.com/eci-instance-spec: 0.25-1.0Gi
                  k8s.aliyun.com/eci-instance-zone: cn-shanghai-b
                  k8s.aliyun.com/eci-kube-proxy-enabled: true
                  k8s.aliyun.com/eci-matched-image-cache: imc-uf6imn4ini7vb8s7740x
                  k8s.aliyun.com/eci-platform-version: 1.1.0
                  k8s.aliyun.com/eci-request-id: D1949770-1BF8-59EB-88A1-C436AF006F6E
                  k8s.aliyun.com/eci-schedule-result: finished
                  k8s.aliyun.com/eci-security-group: sg-uf6c8h2dhscy701vne87
                  k8s.aliyun.com/eci-vpc: vpc-uf60wlj8vkm6o7r4484gf
                  k8s.aliyun.com/eci-vswitch: vsw-uf6dd5seljchrd4s783tb
                  k8s.aliyun.com/eni-instance-id: eni-uf6dvgdshzo7mffzcsq3
                  k8s.aliyun.com/k8s-version: v1.28.3-aliyun.1
                  k8s.aliyun.com/product-on-eci-mode: NA
                  k8s.aliyun.com/vk-version: v2.11.3-2024-03-18-13-07-UTC
                  kubernetes.io/pod-stream-port: 10250
Status:           Running
IP:               10.30.1.130
IPs:
  IP:           10.30.1.130
Controlled By:  ReplicaSet/metersphere-gateway-78899b8f6d
Init Containers:
  wait-mysql:
    Container ID:  containerd://a0a4540d72d1aa2039e03f8cf48aed9b384e0dcb248d5b83574588030ef8707a
    Image:         busybox:latest
    Image ID:      docker.io/library/busybox@sha256:5acba83a746c7608ed544dc1533b87c737a0b0fb730301639a0179f9344b1678
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      set -ex
      until nc -zv metersphere-mysql 3306; do sleep 5; done
      sleep 10
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 17 May 2024 15:53:12 +0800
      Finished:     Fri, 17 May 2024 15:54:22 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-r2lx6 (ro)
Containers:
  metersphere-gateway:
    Container ID:   containerd://adde40023d9d0e91b6df2f32e74a3058a84e731612c037b27b27b5c31da1c311
    Image:          registry.cn-qingdao.aliyuncs.com/metersphere/gateway:v2.10.12-lts
    Image ID:       registry.cn-qingdao.aliyuncs.com/metersphere/gateway@sha256:ede9c50739aa96a2ec015b97c53d86d64b6e25055f96b32a40411ce385153f58
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 17 May 2024 18:03:31 +0800
      Finished:     Fri, 17 May 2024 18:05:38 +0800
    Ready:          False
    Restart Count:  21
    Limits:
      memory:  800Mi
    Requests:
      cpu:     100m
      memory:  300Mi
    Environment:
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS:  true
    Mounts:
      /opt/metersphere/conf from opt-metersphere-config (rw)
      /opt/metersphere/data from metersphere-data (rw)
      /opt/metersphere/logs from metersphere-logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-r2lx6 (ro)
Conditions:
  Type                         Status
  ContainerInstanceCreated     True 
  PodReadyToStartContainers    True 
  Initialized                  True 
  Ready                        False 
  ContainersReady              False 
  PodScheduled                 True 
  ContainerHasSufficientDisk   True 
Volumes:
  opt-metersphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metersphere-config
    Optional:  false
  metersphere-logs:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  metersphere-logs-pvc
    ReadOnly:   false
  metersphere-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  metersphere-data-pvc
    ReadOnly:   false
  scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metersphere-scripts
    Optional:  false
  kube-api-access-r2lx6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  BackOff  37s (x432 over 128m)  kubelet  Back-off restarting failed container metersphere-gateway in pod metersphere-gateway-78899b8f6d-fj5fv_ms(cce3d725-e9bc-4279-bfc8-00c5680370be)
[root@dev-jenkins fency]# 
```
