### ISSUE TITLE
[QUESTION]MS 3.6-lts python3 代码 import requests 无法导入错误咨询

### ISSUE THREAD

**Issue by blackfoamm** [metersphere/metersphere#34917]
### 请描述您的问题

尝试过官网的两种方式（挂载和镜像）来执行 python3 的代码，都会报错无法 import requests 包

镜像的制作方式，主要参考 issue ：[MeterSphere v3.0已经支持Python3，关于Python3引入第三方包的操作说明 #31811](https://github.com/metersphere/metersphere/issues/31811)

步骤和执行截图：
制作镜像
```
FROM registry.fit2cloud.com/metersphere/python:3.10-alpine
 
RUN pip install requests pinyin
 
VOLUME ["/usr/local/lib/python3.10/site-packages"]
```
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/da6fc25e-d5a0-4a4a-92c5-e99979dbe5d4" />

修改task-runner的yml 共享python目录
```
version: "3"
services:
  python:
    container_name: python
    image: python:3.10
    command: sh -c "tail -f /dev/null"  # 保持容器运行
 
  task-runner:
    image: ${MS_IMAGE_PREFIX}/metersphere-ce:${MS_IMAGE_TAG}
    container_name: task-runner
    deploy:
      resources:
        limits:
          memory: ${MS_RUNNER_MEM_LIMIT}
    entrypoint:
      - sh
      - -c
      - |
        sh /shells/task-runner.sh
    environment:
      TOTP_ENABLED: ${MS_TOTP_ENABLED}
      TOTP_SECRET: ${MS_TOTP_SECRET}
    ports:
      - ${MS_TASK_RUNNER_PORT}:8000
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8000" ]
      interval: 6s
      timeout: 5s
      retries: 50
    volumes:
      - ${MS_BASE}/metersphere/logs/task-runner:/opt/metersphere/logs/task-runner
    volumes_from:
      - python
    restart: always
    networks:
      - ms-network
```

重载 ms
```
sudo msctl reload
```
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/15377037-f233-47d6-8c5f-22f38df94d8d" />

通过场景的方式执行 python3 代码

![image](https://github.com/user-attachments/assets/80773c5b-30e8-45c5-a3cd-f13b752944af)
