### ISSUE TITLE
[BUG]MeterSphere- V3  前后置脚本使用Python3 第三方依赖失败

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#35299]
### 联系方式

jiaxin.li

### MeterSphere 版本

v3.6.3-lts

### 使用外置数据库

否

### 问题描述

MeterSphere- V3  前后置脚本使用Python3 第三方依赖失败

### 重现步骤

使用了两种方式：
1.挂载本地python3 依赖目录至task-ruuner容器：/usr/local/lib/python3.10/site-packages ，脚本中指定加载该目录，执行脚本报错org.graalvm.polyglot.PolyglotException: ModuleNotFoundError: No module named 'requests'
2. 容器共享目录方式，参照 文章https://wiki.fit2cloud.com/pages/viewpage.action?pageId=149556865，调试脚本报错：roblem in JSR223 script pyhton-rewuest, message: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: SystemError: NFIUnsatisfiedLinkError: Error relocating /home/appuser/.cache/org.graalvm.polyglot/python/python-home/7f99e649dc51b21db2b83ce56bc9742e402b87c1/lib/graalpy24.1/libpython-native.so: backtrace: symbol not found

### 相关日志输出

```shell

```

**Comment by liuruibin** [comment]
Dockerfile 按照文档提示
```
FROM python:3.11-alpine

RUN pip install requests -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

VOLUME ["/usr/local/lib/python3.11/site-packages"]
```

docker-compose-task-runner.yml 也按照文档来写
```
version: "3"
services:
  python:
    container_name: python
    image: python:3.11-ms
    command: sh -c "tail -f /dev/null"  # 保持容器运行
  task-runner:
    image: ${MS_IMAGE_PREFIX}/metersphere-ee:${MS_IMAGE_TAG}
    container_name: task-runner
    deploy:
      resources:
        limits:
          memory: ${MS_RUNNER_MEM_LIMIT}
    entrypoint:
      - sh
      - -c
      - |
        sh /shells/task-runner.sh
    environment:
      TOTP_ENABLED: ${MS_TOTP_ENABLED}
      TOTP_SECRET: ${MS_TOTP_SECRET}
    ports:
      - ${MS_TASK_RUNNER_PORT}:8000
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8000" ]
      interval: 6s
      timeout: 5s
      retries: 50
    volumes:
      - ${MS_BASE}/metersphere/logs/task-runner:/opt/metersphere/logs/task-runner
    volumes_from:
      - python
    restart: always
    networks:
      - ms-network
```

demo环境中已经测试 你可以自己去测试https://demo.metersphere.com/
